// Code generated by "stringer -type=Dato"; DO NOT EDIT.

package main

import "fmt"

const _Dato_name = "NuloTensionLineaRTensionLineaSTensionLineaTCorrienteLineaRCorrienteLineaSCorrienteLineaTCorrienteNAnguloSAnguloTFrecuenciaRFrecuenciaSFrecuenciaTDesfaseRSDesfaseSTDesfaseTR"

var _Dato_index = [...]uint8{0, 4, 17, 30, 43, 58, 73, 88, 98, 105, 112, 123, 134, 145, 154, 163, 172}

func (i Dato) String() string {
	if i < 0 || i >= Dato(len(_Dato_index)-1) {
		return fmt.Sprintf("Dato(%d)", i)
	}
	return _Dato_name[_Dato_index[i]:_Dato_index[i+1]]
}
